site_name: moudrick.net
site_description: "Personal experiments, projects, and notes by moudrick."
site_url: https://moudrick.net

copyright: >
  Copyright &copy; 2025 moudrick –
  <a href="#__consent">Change cookie settings</a>

plugins:
  - search
  - blog:
      blog_dir: blog
      draft: true
      blog_toc: true

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch dark/light mode automatically by user's OS
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: green
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  consent:
    title: "Cookie consent"
    description: "We use cookies to improve your experience and analyze traffic."
    actions:
      - accept
      - reject
  analytics:
    provider: google
    property: G-R85H8F8QQ2

extra_css:
  - extra_css/home.css
  - extra_css/custom.css

extra_javascript:
  - extra_javascript/nav_external.js

markdown_extensions:
  - attr_list

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Projects: projects/index.md
  - GitHub: https://github.com/moudrick
